server:
  port: 8081
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    url: jdbc:mysql://localhost:3306/poetry_clean?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    root: info
    com.example.poetry.backend: debug

app:
  avatar:
    upload-dir: ./data/uploads
    public-base-url: ""
  verification-code:
    # Verification code expiry (minutes)
    expiry-minutes: 5
    # Verification code length
    code-length: 6

security:
  jwt:
    secret: "poetry-dev-secret-please-change-32bytes-minimum-2026-04-27"
    expiration-seconds: 604800

deepseek:
  api:
    key: sk-761aebfab47741daaf174c6377200349
    url: https://api.deepseek.com

anthropic:
  api:
    key: ark-a934a5d9-95bc-4ea5-b923-61cde6e5bbb8-5c329